---
base_url: "https://www.studierendenwerk-aachen.de"
mensas:
  - id: "mensa-academica"
    name: "Mensa Academica"
    urls:
      de: "{BASE_URL}/speiseplaene/academica-w.html"
      en: "{BASE_URL}/speiseplaene/academica-w-en.html"
  - id: "mensa-ahorn"
    name: "Mensa Ahornstraße"
    urls:
      de: "{BASE_URL}/speiseplaene/ahornstrasse-w.html"
      en: "{BASE_URL}/speiseplaene/ahornstrasse-w-en.html"
  - id: "bistro-templergraben"
    name: "Bistro Templergraben"
    urls:
      de: "{BASE_URL}/speiseplaene/templergraben-w.html"
      en: "{BASE_URL}/speiseplaene/templergraben-w-en.html"
  - id: "mensa-bayernallee"
    name: "Mensa Bayernallee"
    urls:
      de: "{BASE_URL}/speiseplaene/bayernallee-w.html"
      en: "{BASE_URL}/speiseplaene/bayernallee-w-en.html"
  - id: "mensa-eupener-strasse"
    name: "Mensa Eupener Straße"
    urls:
      de: "{BASE_URL}/speiseplaene/eupenerstrasse-w.html"
      en: "{BASE_URL}/speiseplaene/eupenerstrasse-w-en.html"
  - id: "mensa-kmac"
    name: "Mensa KMAC"
    urls:
      de: "{BASE_URL}/speiseplaene/kmac-w.html"
      en: "{BASE_URL}/speiseplaene/kmac-w-en.html"
  - id: "mensa-südpark"
    name: "Mensa Südpark"
    urls:
      de: "{BASE_URL}/speiseplaene/suedpark-w.html"
      en: "{BASE_URL}/speiseplaene/suedpark-w-en.html"
  - id: "mensa-vita"
    name: "Mensa Vita"
    urls:
      de: "{BASE_URL}/speiseplaene/vita-w.html"
      en: "{BASE_URL}/speiseplaene/vita-w-en.html"
  - id: "mensa-juelich"
    name: "Mensa Jülich"
    urls:
      de: "{BASE_URL}/speiseplaene/juelich-w.html"
      en: "{BASE_URL}/speiseplaene/juelich-w-en.html"
