---
services:
    dynamodb:
        image: amazon/dynamodb-local
        ports:
        - "8000:8000"
        command: "-jar DynamoDBLocal.jar -sharedDb"
    webhost:
        build: ./rwth-mensa-dummy
        ports:
            - "8081:80"
