AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM APP for the rwth-mensa-buttler.
  Used for configuring the scrapping lambda function and the dynamoDB table.
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON


Parameters:
    TABLENAME:
        Type: String
        Description: DynamoDB Table Name
        Default: MensaOfferings
    ENVIRONMENTNAME:
        Type: String
        Description: Environment Name (prod, localdev)
        Default: prod
    ALEXASKILLARN:
        Type: String
        Description: ARN of the Alexa Skill

Resources:
  MensaOfferingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TABLENAME
      AttributeDefinitions:
        - AttributeName: MensaIdLanguageKeyDate
          AttributeType: S
      KeySchema:
        - AttributeName: MensaIdLanguageKeyDate
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  AlexaMensaOfferingsTableAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref ALEXASKILLARN
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AlexaMensaOfferingsTableAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: !GetAtt MensaOfferingsTable.Arn

  ScrapMensaDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt MensaOfferingsTable.Arn
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        HourlyScan:
          Type: Schedule
          Properties:
            Schedule: rate(4 hours)
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TABLE_NAME: !Ref TABLENAME
          ENVIRONMENT_NAME: !Ref ENVIRONMENTNAME
    Metadata:
      DockerTag: provided.al2-v1
      DockerContext: ../
      Dockerfile: menu-scrapper-lambda/Dockerfile

Outputs:
  ScrapMensaDataFunction:
    Description: A Lambda ARN for the regular mensa scraping function
    Value: !GetAtt ScrapMensaDataFunction.Arn
  MensaOfferingsTable:
    Description: A Table ARN for the mensa offerings
    Value: !GetAtt MensaOfferingsTable.Arn

