---
name: CI pipeline

on: ['push']

jobs:
  menu-scrapper-lib-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.9'

      - name: Install dependencies
        working-directory: ./menu-scrapper-lib
        run: go get -d ./...

      - name: Run tests
        working-directory: ./menu-scrapper-lib
        run: go test -v ./test

      - name: Lint code
        if: '!cancelled()'
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.1
